on: [push]

jobs:
  somename:
    runs-on: ubuntu-latest
    name: Upload GDS data to Sumo Logic
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2
      with:
        ref: 'main'
    - name: Populate Sumo Logic Lookup
      id: upload
      uses: datfinesoul/sample-action@v0.0.4
      with:
        sumologic_config: ${{ secrets.SUMO_LOGIC_API_ACCESS_SECRET }}
    # Use the output from the `hello` step
    #- name: Get the output time
      #run: echo "The time was ${{ steps.hello.outputs.time }}"
